# Generated by Django 5.2 on 2025-09-20 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la presentación', max_length=200)),
                ('pdf_file', models.FileField(help_text='Archivo PDF de la presentación', upload_to='presentations/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('total_slides', models.PositiveIntegerField(default=0, help_text='Número total de slides en la presentación')),
                ('is_converted', models.BooleanField(default=False, help_text='Indica si el PDF ya fue convertido a imágenes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField(help_text='Número del slide dentro de la presentación')),
                ('image_file', models.ImageField(help_text='Imagen del slide convertida desde PDF', upload_to='presentations/slides/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('presentation', models.ForeignKey(help_text='Presentación a la que pertenece este slide', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['presentation', 'slide_number'],
                'unique_together': {('presentation', 'slide_number')},
            },
        ),
    ]
