# Generated by Django 5.2 on 2025-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', help_text='Estado actual del procesamiento del PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='presentation',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea Celery para seguimiento', max_length=50, null=True),
        ),
    ]
